# Generated by Django 6.0.2 on 2026-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_sim_prediction_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureeventsHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('stay_id', models.IntegerField()),
                ('charttime_hour', models.DateTimeField(blank=True, null=True)),
                ('charttime', models.DateTimeField(blank=True, null=True)),
                ('caregiver_id', models.IntegerField(blank=True, null=True)),
                ('itemid', models.IntegerField(blank=True, null=True)),
                ('item_label', models.CharField(blank=True, max_length=100, null=True)),
                ('item_unitname', models.CharField(blank=True, max_length=50, null=True)),
                ('item_lownormalvalue', models.FloatField(blank=True, null=True)),
                ('item_highnormalvalue', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('valueuom', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('locationcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('orderid', models.IntegerField(blank=True, null=True)),
                ('linkorderid', models.IntegerField(blank=True, null=True)),
                ('ordercategoryname', models.CharField(blank=True, max_length=50, null=True)),
                ('ordercategorydescription', models.CharField(blank=True, max_length=30, null=True)),
                ('patientweight', models.FloatField(blank=True, null=True)),
                ('isopenbag', models.SmallIntegerField(blank=True, null=True)),
                ('continueinnextdept', models.SmallIntegerField(blank=True, null=True)),
                ('statusdescription', models.CharField(blank=True, max_length=20, null=True)),
                ('originalamount', models.FloatField(blank=True, null=True)),
                ('originalrate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fisi9t_procedureevents_hourly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniquePatientProfile',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stay_id', models.IntegerField()),
                ('hadm_id', models.IntegerField()),
                ('anchor_age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('race', models.CharField(blank=True, max_length=80, null=True)),
                ('first_careunit', models.CharField(blank=True, max_length=255, null=True)),
                ('last_careunit', models.CharField(blank=True, max_length=255, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('los', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fisi9t_unique_patient_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VitalsignHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('stay_id', models.IntegerField()),
                ('charttime_hour', models.DateTimeField()),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('sbp', models.FloatField(blank=True, null=True)),
                ('dbp', models.FloatField(blank=True, null=True)),
                ('mbp', models.FloatField(blank=True, null=True)),
                ('sbp_ni', models.FloatField(blank=True, null=True)),
                ('dbp_ni', models.FloatField(blank=True, null=True)),
                ('mbp_ni', models.FloatField(blank=True, null=True)),
                ('resp_rate', models.FloatField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_site', models.TextField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fisi9t_vitalsign_hourly',
                'managed': False,
            },
        ),
    ]
