# Generated by Django 5.2.12 on 2026-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_register_unmanaged_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsofahourly',
            name='pao2fio2ratio_novent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simsofahourly',
            name='pao2fio2ratio_vent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simsofahourly',
            name='rate_dobutamine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simsofahourly',
            name='rate_dopamine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simsofahourly',
            name='rate_epinephrine',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='simsofahourly',
            name='rate_norepinephrine',
            field=models.FloatField(null=True),
        ),
    ]
